---
title: "Publications"
output: html_document
---

<div style="width:80%;margin: auto;">

<br>

##  {.tabset}

### Peer-reviewed publications

[Models for emergent structures in mobility: specification and individual-level interpretation](https://academic.oup.com/jrsssa/advance-article/doi/10.1093/jrsssa/qnag057/8659714)<br>M Hoffman & P Block<br>*Journal of the Royal Statistical Society Series A: Statistics in Society*, 2026

[Dyadic Isolation in Social Interactions: The Role of Depressive Symptoms](https://journals.sagepub.com/doi/10.1177/01902725241276407)<br>M Hoffman, C Stadtfeld, T Elmer<br>*Social Psychology Quaterly*, 2025

[Social and spatial predictors of collective search behaviors](https://www.nature.com/articles/s41598-025-02460-7)<br>M Hoffman, T Thrash, C Hölscher, M Kapadia, VR Schinazi<br>*Scientific Reports*, 2025

[Antecedents of student team formation in higher education](https://www.sciencedirect.com/science/article/pii/S0959475224000586)<br>CA de Matos Fernandes, M Hoffman & J Brouwer<br>*Learning and Instruction*, 2024

[The role of selection in socioeconomic homophily: Evidence from an adolescent summer camp](https://www.sciencedirect.com/science/article/pii/S0378873323000291)<br>M Hoffman & T Chabot<br>*Social Networks*, 2023

[Modeling partitions of individuals](https://journals.sagepub.com/doi/abs/10.1177/00811750221145166)<br>
M Hoffman, P Block, TAB Snijders<br>
*Sociological Methodology*, 2023

[The Swiss StudentLife Study: Codebook](https://www.sciencedirect.com/science/article/pii/S037887332030099X)<br>
T Elmer, K Mepham, M Hoffman, Z Boda, IJ Raabe, A Vörös & C Stadtfeld<br>
*PsyArXiv*, 2022 [not peer-reviewed]

[The Swiss StudentLife Study: Investigating the emergence of an undergraduate community through dynamic, multidimensional social network data](https://www.sciencedirect.com/science/article/pii/S037887332030099X)<br>
A Vörös, Z Boda, T Elmer, M Hoffman, K Mepham, IJ Raabe & C Stadtfeld<br>
*Social Networks*, 2021

[Social network-based distancing strategies to flatten the COVID-19 curve in a post-lockdown world](https://www.nature.com/articles/s41562-020-0898-6)<br>
P Block, M Hoffman, IJ Raabe, JB Dowd, C Rahal, R Kashyap & MC Mills<br>
*Nature Human Behaviour*, 2020

[A model for the dynamics of face-to-face interactions in social groups](https://www.cambridge.org/core/journals/network-science/article/model-for-the-dynamics-of-facetoface-interactions-in-social-groups/5EE32074370B3C443EE9AA2519602338)<br>
M Hoffman, P Block, T Elmer & C Stadtfeld<br>
*Network Science*, 2020

[Social network analysis of DFAB house: a demonstrator of digital fabrication in construction](https://www.research-collection.ethz.ch/handle/20.500.11850/388870)<br>
K Graser, Y Wang, M Hoffman, MM Bonanomi, M Kohler & D Hall<br>
*Proceedings of EPOC*, 2019

---

### Conference presentations

**Micro-level interpretation of statistical models for social groups – A game theoretical approach**<br>
M Hoffman, P Bayer, M Keijzer, V Amati<br>
*19th Annual Conference of the International Network of Analytical Sociology, Oxford, UK*, 2026, Jul 1-3

**Modeling emergent structures in mobility networks**<br>
M Hoffman, P Block, C Noack<br>
*45th Sunbelt Conference, Paris, France* 2025, Jun 23-28

**Modeling emergent structures in mobility networks**<br>
M Hoffman, P Block, C Noack<br>
*Atelier Réseaux Sociaux du Labex SMS, Toulouse, France* 2025, Jun 19

**An agent-based interpretation of exponential family models for graphs and partitions**<br>
M Hoffman<br>
*Workshop on Empirically-Calibrated Agent-Based Models for Mechanism-Based Research, Toulouse, France*, 2024, Dec 11-13

**Modeling the mechanisms driving the co-constitution of groups and individuals at the Commercial Court of Paris**<br>
M Hoffman & E Lazega<br>
*44th Sunbelt Conference, Edinburgh, UK*, 2024, Jun 24-30

**From movement comes stability: Modeling the mechanisms driving the co-constitution of groups and individuals at the Commercial Court of Paris**<br>
M Hoffman & E Lazega<br>
*Duality Workshop, ETH Zürich, Switzerland*, 2024, Apr 15-18

**Specifying attribute effects in statistical models for groups – A game theoretical approach**<br>
M Hoffman, P Bayer, M Keijzer, V Amati<br>
*ARS'23 Ninth International Workshop on Social Network Analysis, Naples, Italy*, 2023, May 2-3

**Specification of attribute effects in statistical models for social groups**<br>
M Hoffman<br>
*6th European Conference on Social Networks, Greenwich, UK*,2022, Sep 12-16

**Dynamics of group-based meetings amongst teenagers**<br>
M Hoffman & T Chabot<br>
*RC33 conference, online*, 2021, Sep 7-10

**The Role of Preference-Based Selection in Socioeconomic Homophily: Evidence from a Three-Week Summer Camp**<br>
M Hoffman & T Chabot<br>
*6th European Conference on Social Networks, online*, 2021, Sep 6-10

**Social network-based distancing strategies to flatten the COVID-19 curve in a post-lockdown world**<br>
P Block, M Hoffman, IJ Raabe, JB Dowd, C Rahal, R Kashyap, MC Mills<br>
*Costnet Conference on Covid-19, Munich, Germany*, 2020, Jul 10

**From dyads to groups: A partition model for non-overlapping groups**<br>
M Hoffman, P Block, TAB Snijders<br> 
*40th Sunbelt Conference, Paris, France (online)*, 2020, Jul 13-17 

**A partition model for membership of non-overlapping groups**<br>
M Hoffman, P Block, TAB Snijders<br>
*4th European Conference on Social Networks, Zürich, Switzerland*, 2019, Sep 9-12

**DyNAM-i: a statistical model for the analysis of face-to-face interactions**<br>
M Hoffman, P Block P, T Elmer, C Stadtfeld<br>
*7th International Conference on Complex Networks and Their Applications, Cambridge, UK*, 2018, Dec 11-13

**A statistical model for the analysis of face-to-face interactions**<br>
M Hoffman, P Block, T Elmer, C Stadtfeld<br> 
*38th Sunbelt Conference, Utrecht, the Netherlands*, 2018, Jun 26 - Jul 1


---

### Invited talks

The Institute for Analytical Sociology Seminar, **Linköping University**, Sweden (2026 Apr 16)

Statistics seminar series, jointly hosted by **Trinity College Dublin** and **University College Dublin**, Ireland (2025 Dec 4)

Statistic Seminar, **Carnegie Mellon University**, online (2025 Sep 12)

Statistics Seminar, **University of New South Wales**, Australia (2024 Nov 25)

Satellite Symposium “Statistical Inference for Network Models”, **NetSci 2023 Conference** in Vienna, Austria (2023 July 11)

Statistics seminar, **University of Kent**, online (2023 Mar 16)

Séminaire Savoir, réseaux, et médiation, **Université Toulouse Jean Jaurès**, France (2023 Jan 27)

Mathematics and Statistics seminar, **Toulouse School of Economics**, France (2022 Dec 8)

Symposium on Social network and demographic models, **CEFE-CNRS, University of Montpellier**, France (2022 Oct 10-11)

Mitchell Center Seminar, **University of Manchester**, UK (2022 Feb 23)

Invited talk at the **Costnet Conference on Covid-19**, online (2020 Jul 10)

Seminar of the Leverhulme Centre for Demographic Science, **University of Oxford**, UK (2020 Mar 11)

Sociology Colloquium, **University of Groningen**, The Netherlands (2019 Nov 27)


</div>



<!--

## Some tabs {.tabset}

### Tab 1

Content

---

### Tab 2

Content

---

## {.unlisted}

### Yes?

</div>

-->

```{js,echo=F}
$(function() {
	$(".navbar-nav").hide();
	});
```
